import {
  Baby,
  Bath,
  Briefcase,
  CheckCircle2,
  Coffee,
  CookingPot,
  Dice5,
  Fan,
  Flame,
  type LucideIcon,
  Home,
  KeyRound,
  Landmark,
  Microwave,
  Refrigerator,
  ShieldAlert,
  ShoppingBag,
  Shirt,
  Snowflake,
  Speaker,
  Sparkles,
  Table2,
  Trash2,
  Trees,
  Tv,
  Umbrella,
  Utensils,
  UtensilsCrossed,
  Car,
  Warehouse,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
  Wine,
} from "lucide-react";

const RULES: [RegExp, LucideIcon][] = [
  [/wireless internet|wifi|internet/i, Wifi],
  [/garage/i, Warehouse],
  [/park/i, Car],
  [/kitchen/i, UtensilsCrossed],
  [/\btv\b/i, Tv],
  [/wash|laundry|dryer/i, WashingMachine],
  [/air condition/i, Snowflake],
  [/ice maker/i, Snowflake],
  [/heat/i, Flame],
  [/fire pit/i, Flame],
  [/oven|stove|cook/i, CookingPot],
  [/microwave/i, Microwave],
  [/coffee/i, Coffee],
  [/wine/i, Wine],
  [/refrigerator|freezer/i, Refrigerator],
  [/dish|silverware|toaster/i, Utensils],
  [/bath|tub/i, Bath],
  [/hair dryer/i, Wind],
  [/iron|hanger|clothing storage/i, Shirt],
  [/detector|extinguisher|first aid/i, ShieldAlert],
  [/fan/i, Fan],
  [/sound system/i, Speaker],
  [/garden|backyard/i, Trees],
  [/patio|balcony|outdoor/i, Umbrella],
  [/single level home/i, Home],
  [/long term stays/i, Home],
  [/workspace|laptop/i, Briefcase],
  [/smart lock|keyless/i, KeyRound],
  [/children|infant/i, Baby],
  [/casino/i, Dice5],
  [/museum/i, Landmark],
  [/shopping/i, ShoppingBag],
  [/water park/i, Waves],
  [/dining table/i, Table2],
  [/essentials/i, Sparkles],
  [/clean/i, Sparkles],
  [/trash compactor/i, Trash2],
  [/soap|shampoo|conditioner|shower gel|hot water|towel/i, Bath],
];

export function getAmenityIcon(label: string): LucideIcon {
  const match = RULES.find(([pattern]) => pattern.test(label));
  return match ? match[1] : CheckCircle2;
}
